/**
 * Standup Notes Panel Plugin
 *
 * Panel for quickly capturing and sharing daily standup notes.
 * Auto-populates with recent activity from git history.
 */

import type { PanelPlugin, PluginContext, Commit } from '../plugin-types'

/**
 * Standup note structure
 */
interface StandupNote {
  date: string
  yesterday: string[]
  today: string[]
  blockers: string[]
  autoGenerated: {
    commits: Commit[]
    prsOpened: number
    prsMerged: number
  }
}

/**
 * Standup Notes Panel
 *
 * Features:
 * - Auto-populate "Yesterday" from git history
 * - Quick input for today's plans
 * - Blocker tracking
 * - Copy to clipboard for Slack/Teams
 * - History of past standups
 */
export const standupNotesPlugin: PanelPlugin = {
  id: 'ledger.standup-notes',
  name: 'Standup Notes',
  version: '1.0.0',
  type: 'panel',
  description: 'Quick daily standup notes with auto-populated git activity',
  author: 'Ledger Team',
  permissions: ['git:read', 'notifications'],

  // Panel configuration
  title: 'Daily Standup',
  component: 'StandupNotesPanel',
  size: 'medium',
  position: 'center',
  closable: true,
  shortcut: 'Cmd+Shift+S',

  // Settings
  settings: [
    {
      key: 'template',
      label: 'Note template',
      type: 'select',
      default: 'standard',
      options: [
        { label: 'Standard (Yesterday/Today/Blockers)', value: 'standard' },
        { label: 'Compact', value: 'compact' },
        { label: 'Detailed', value: 'detailed' },
      ],
    },
    {
      key: 'autoPopulate',
      label: 'Auto-populate yesterday',
      description: 'Fill in yesterday section from git history',
      type: 'boolean',
      default: true,
    },
    {
      key: 'includeStats',
      label: 'Include statistics',
      description: 'Add commit/PR counts to notes',
      type: 'boolean',
      default: true,
    },
    {
      key: 'reminder',
      label: 'Daily reminder',
      description: 'Show notification to fill standup notes',
      type: 'boolean',
      default: false,
    },
    {
      key: 'reminderTime',
      label: 'Reminder time',
      type: 'string',
      default: '09:00',
    },
  ],

  // Commands
  commands: [
    {
      id: 'ledger.standup-notes.open',
      name: 'Open Standup Notes',
      description: 'Open the standup notes panel',
      shortcut: 'Cmd+Shift+S',
      handler: async () => {
        console.log('[Standup Notes] Opening panel...')
      },
    },
    {
      id: 'ledger.standup-notes.copy',
      name: 'Copy Standup to Clipboard',
      description: 'Copy today\'s standup notes to clipboard',
      handler: async () => {
        console.log('[Standup Notes] Copying to clipboard...')
      },
    },
  ],

  async activate(context: PluginContext): Promise<void> {
    context.logger.info('Standup Notes activated')

    // Load saved notes
    const savedNotes = await context.storage.get<StandupNote[]>('notes')
    context.logger.debug('Loaded', savedNotes?.length ?? 0, 'saved standups')

    // Check for reminder setting
    const reminder = await context.storage.get<boolean>('reminder')
    if (reminder) {
      context.logger.debug('Daily reminder enabled')
    }
  },

  async deactivate(): Promise<void> {
    console.log('[Standup Notes] Panel deactivated')
  },
}

export default standupNotesPlugin
