/**
 * Standup Notes Panel Plugin
 *
 * Panel for quickly capturing and sharing daily standup notes.
 * Auto-populates with recent activity from git history.
 */

import type { PanelPlugin, PluginContext, Commit } from '../plugin-types'

/**
 * Standup note structure
 */
interface StandupNote {
  date: string
  yesterday: string[]
  today: string[]
  blockers: string[]
  autoGenerated: {
    commits: Commit[]
    prsOpened: number
    prsMerged: number
  }
}

/**
 * Standup Notes Panel
 *
 * Features:
 * - Auto-populate "Yesterday" from git history
 * - Quick input for today's plans
 * - Blocker tracking
 * - Copy to clipboard for Slack/Teams
 * - History of past standups
 */
export const standupNotesPlugin: PanelPlugin = {
  id: 'ledger.standup-notes',
  name: 'Standup Notes',
  version: '1.0.0',
  type: 'panel',
  description: 'Quick daily standup notes with auto-populated git activity',
  author: 'Ledger Team',
  permissions: ['git:read', 'storage', 'notifications'],

  // Panel configuration
  title: 'Daily Standup',
  component: 'StandupNotesPanel',
  size: 'medium',
  position: 'center',
  closable: true,
  shortcut: 'Cmd+Shift+S',

  // Settings
  settings: [
    {
      key: 'template',
      label: 'Note template',
      type: 'select',
      default: 'standard',
      options: [
        { label: 'Standard (Yesterday/Today/Blockers)', value: 'standard' },
        { label: 'Compact', value: 'compact' },
        { label: 'Detailed', value: 'detailed' },
      ],
    },
    {
      key: 'autoPopulate',
      label: 'Auto-populate yesterday',
      description: 'Fill in yesterday section from git history',
      type: 'boolean',
      default: true,
    },
    {
      key: 'includeStats',
      label: 'Include statistics',
      description: 'Add commit/PR counts to notes',
      type: 'boolean',
      default: true,
    },
    {
      key: 'reminder',
      label: 'Daily reminder',
      description: 'Show notification to fill standup notes',
      type: 'boolean',
      default: false,
    },
    {
      key: 'reminderTime',
      label: 'Reminder time',
      type: 'string',
      default: '09:00',
    },
  ],

  // Commands
  commands: [
    {
      id: 'ledger.standup-notes.open',
      name: 'Open Standup Notes',
      description: 'Open the standup notes panel',
      shortcut: 'Cmd+Shift+S',
      handler: async () => {
        console.log('[Standup Notes] Opening panel...')
      },
    },
    {
      id: 'ledger.standup-notes.copy',
      name: 'Copy Standup to Clipboard',
      description: 'Copy today\'s standup notes to clipboard',
      handler: async () => {
        console.log('[Standup Notes] Copying to clipboard...')
      },
    },
  ],

  async activate(context: PluginContext): Promise<void> {
    context.logger.info('Standup Notes activated')

    // Load saved notes
    const savedNotes = await context.storage.get<StandupNote[]>('notes')
    context.logger.debug('Loaded', savedNotes?.length ?? 0, 'saved standups')

    // Check for reminder setting
    const reminder = await context.storage.get<boolean>('reminder')
    if (reminder) {
      context.logger.debug('Daily reminder enabled')
    }
  },

  async deactivate(): Promise<void> {
    console.log('[Standup Notes] Panel deactivated')
  },
}

/**
 * Generate standup content from git history
 */
function generateYesterdayContent(
  commits: Commit[],
  includeStats: boolean
): string[] {
  const items: string[] = []

  // Group commits by type
  const features = commits.filter((c) => c.message.toLowerCase().startsWith('feat'))
  const fixes = commits.filter((c) => c.message.toLowerCase().startsWith('fix'))
  const other = commits.filter(
    (c) =>
      !c.message.toLowerCase().startsWith('feat') &&
      !c.message.toLowerCase().startsWith('fix')
  )

  if (features.length > 0) {
    items.push(`Implemented ${features.length} new feature${features.length > 1 ? 's' : ''}`)
  }

  if (fixes.length > 0) {
    items.push(`Fixed ${fixes.length} bug${fixes.length > 1 ? 's' : ''}`)
  }

  if (other.length > 0) {
    items.push(`Made ${other.length} other update${other.length > 1 ? 's' : ''}`)
  }

  if (includeStats && commits.length > 0) {
    const totalAdditions = commits.reduce((sum, c) => sum + (c.additions ?? 0), 0)
    const totalDeletions = commits.reduce((sum, c) => sum + (c.deletions ?? 0), 0)
    items.push(`Lines changed: +${totalAdditions} / -${totalDeletions}`)
  }

  return items.length > 0 ? items : ['No activity recorded']
}

/**
 * Format standup for clipboard/sharing
 */
function formatStandupForSharing(note: StandupNote, template: string): string {
  switch (template) {
    case 'compact':
      return [
        `📅 ${note.date}`,
        `✅ ${note.yesterday.join(', ')}`,
        `🎯 ${note.today.join(', ')}`,
        note.blockers.length > 0 ? `🚧 ${note.blockers.join(', ')}` : '',
      ]
        .filter(Boolean)
        .join('\n')

    case 'detailed':
      return [
        `# Daily Standup - ${note.date}`,
        '',
        '## Yesterday',
        ...note.yesterday.map((item) => `- ${item}`),
        '',
        '## Today',
        ...note.today.map((item) => `- ${item}`),
        '',
        note.blockers.length > 0 ? '## Blockers' : '',
        ...note.blockers.map((item) => `- ⚠️ ${item}`),
        '',
        '---',
        `📊 Commits: ${note.autoGenerated.commits.length}`,
        `📝 PRs Opened: ${note.autoGenerated.prsOpened}`,
        `✅ PRs Merged: ${note.autoGenerated.prsMerged}`,
      ]
        .filter((line) => line !== undefined)
        .join('\n')

    default: // standard
      return [
        `**${note.date}**`,
        '',
        '*Yesterday:*',
        ...note.yesterday.map((item) => `• ${item}`),
        '',
        '*Today:*',
        ...note.today.map((item) => `• ${item}`),
        '',
        note.blockers.length > 0 ? '*Blockers:*' : '',
        ...note.blockers.map((item) => `• 🚧 ${item}`),
      ]
        .filter((line) => line !== undefined)
        .join('\n')
  }
}

export default standupNotesPlugin
